#!/bin/bash

if [ -z $1 ]
	then exit 3
fi

IP=$1;

if [[ $IP =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
	OIFS=$IFS
        IFS='.'
        IP=($IP)
        IFS=$OIFS
	[[ ${IP[0]} -le 255 && ${IP[1]} -le 255 && ${IP[2]} -le 255 && ${IP[3]} -le 255 ]] 
	exit $?    
fi

exit 2
