#!/bin/bash

PING_TIMES=10

## Function for interpreting ping resaults
eval_ping()
{
        pl=$1
        dl=$2

	if [[ $pl -eq 100 ]]; then echo "Remote host is unavailable"; exit; fi

	if [[ $pl -ge 2 ]] && [[ $pl -le 3 ]]; then echo "there is some packet loss"; fi
	if [[ $pl -ge 4 ]]; then echo "there is severe packet loss"; fi		

	if (( $(echo "$dl > 150" |bc -l) )); then echo "there is serious traffic delay"; exit; fi 
	if (( $(echo "$dl > 90" |bc -l) )); then echo "there is moderate traffic delay"; exit; fi	

	echo "RTT is normal, no packetloss, delay is lower then 90ms"
        return
}

## Checking if Google DNS 8.8.8.8 resolves name google.com. If yes - that means Internet works fine
if [ -f dns_dig ];
then
	ip=$( ./dns_dig )
	if [ $? -eq 0 ];
	then
		echo "Remote DNS is available."
	elif [ $? -eq 1 ];
	then
		echo "Remote DNS (8.8.8.8) did not respond"
	fi
fi

## Scannig host google.com.ua for opened ports 21,25,80,443,123. If at least one of them is opened then we have Internet
if [ -f port_scan ];
then
        ./port_scan
        if [ $? -eq 0 ];
        then
                echo "Internet connectivity confirmed"
        else
                echo "Common ports are unavailable. Looks like there is Internet connectivity issue."
        fi
fi

## Pinging 8.8.8.8 to check if there is ICMP connectivity
if [ -f pinger ];
then
	loss_delay=$( ./pinger 8.8.8.8 $PING_TIMES)
	echo "Testing RTT to remote host..."
	eval_ping $loss_delay	
	exit 0;
fi

## Retrieve default Gateway Interface
if [ -f get_default_int ]; 
then
	default_int=$( ./get_default_int )
	if [ $? -eq 1 ]; then 
		echo "No Default Interface - internet can't work"; 
		# If there is no default gateway - internet can't work
		exit 1;
	fi
fi

## Retrieve default Gateway IP
if [ -f get_default_gw ]; 
then
        default_gw=$( ./get_default_gw )
        if [ $? -eq 1 ]; then
                echo "No Default IP";
                # If there is no default gateway IP - internet can't work
               exit 2;
        fi
fi

## Trying to ping default gateway to check if there is connectivity there
if [[ $default_gw =~ ^$ ]] && [[ -f pinger ]];
then
        lossg_delayg=$( ./pinger $default_gw $PING_TIMES )
        echo "Testing RTT to gateway..."
        eval_ping $lossg_delayg
fi
